config/routes.rb
PortfolioManager::Application.routes.draw do
  resources :holdings

  root :to => 'holdings#index'

end

app/models/holding.rb
class Holding < ActiveRecord::Base
  validates :symbol, :price, :qty, presence: true
  validates :price, :qty, numericality: true
  validate :must_be_valid_symbol

  def must_be_valid_symbol
    errors.add(:symbol, "unknown symbol") unless is_valid
  end
end

app/models/yahoo_finance.rb
require 'mechanize'
require 'csv'

class YahooFinance
  
  def self.market_details(symbol)
    yf = self.new
    yf.market_details(symbol) 
  end

  def market_details(symbol)
    agent = Mechanize.new
    result = agent.get("http://finance.yahoo.com/d/quotes.csv?s=#{symbol}&f=snabghn4e1").body
    parse_collection(remove_malformed_csv(result))
  end

  private

  def parse_collection(results)
    CSV.parse(results, :headers => false) do |row| 
      valid = row[7].eql?('invalid') ? false : true
      return { name: row[1], 
               ask: row[2].to_f, 
               bid: row[3].to_f, 
               daily_low: row[4].to_f,
               daily_high: row[5].to_f,
               notes: row[6],
               is_valid: valid}
    end
  end

  def remove_malformed_csv(result)
    result.gsub(/No such ticker symbol.+\)/, 'invalid')
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/holdings_controller.rb
class HoldingsController < ApplicationController
  
  #As the spec states this is single user only just going to do some 
  #simple authentication.  I could move the user name and password to a 
  #config file but this shows the concept
  http_basic_authenticate_with :name => "name", :password => "password"  
  before_filter :get_market_values, :only => [:create, :update]

  # GET /holdings
  # GET /holdings.json
  def index
    @holdings = Holding.select("*, ((bid - price) * qty) as gain")

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @holdings }
    end
  end

  # GET /holdings/1
  # GET /holdings/1.json
  def show
    #@holding = Holding.find(params[:id])
    @holding = Holding.select("*, ((bid - price) * qty) as gain").where(id: params[:id]).first

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @holding }
    end
  end

  # GET /holdings/new
  # GET /holdings/new.json
  def new
    @holding = Holding.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @holding }
    end
  end

  # GET /holdings/1/edit
  def edit
    @holding = Holding.find(params[:id])
  end

  # POST /holdings
  # POST /holdings.json
  def create
    @holding = Holding.new(params[:holding].merge(@yahoo_data))

    respond_to do |format|
      if @holding.save
        format.html { redirect_to @holding, notice: 'Holding was successfully created.' }
        format.json { render json: @holding, status: :created, location: @holding }
      else
        format.html { render action: "new" }
        format.json { render json: @holding.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /holdings/1
  # PUT /holdings/1.json
  def update
    @holding = Holding.find(params[:id])

    respond_to do |format|
      if @holding.update_attributes(params[:holding].merge(@yahoo_data))
        format.html { redirect_to @holding, notice: 'Holding was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @holding.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /holdings/1
  # DELETE /holdings/1.json
  def destroy
    @holding = Holding.find(params[:id])
    @holding.destroy

    respond_to do |format|
      format.html { redirect_to holdings_url }
      format.json { head :no_content }
    end
  end

  private

  def get_market_values
    @yahoo_data = YahooFinance.market_details(params[:holding][:symbol])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/holdings_helper.rb
module HoldingsHelper
  def sum_portfolio
    @holdings.inject(0) {|sum, i| sum + i.gain.to_i }
  end
end

app/views/holdings/_form.html.erb
<%= simple_form_for @holding, :html => { :class => 'form-horizontal' }, :validate => true do |f| %>
  <div class="control-group">
    <%= f.input :symbol, :input_html => {:class => 'test_field'}, :label => "Symbol", :required => false %>
  </div>
  <div class="control-group">
    <%= f.input :price, :input_html => {:class => 'test_field'}, :label => "Price", :required => false %>
  </div>
  <div class="control-group">
    <%= f.input :qty, :input_html => {:class => 'test_field'}, :label => "Qty", :required => false %>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                holdings_path, :class => 'btn' %>
  </div>
<% end %>

app/views/holdings/edit.html.erb
<%- model_class = Holding -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/holdings/index.html.erb
<%- model_class = Holding -%>
<div class="page-header">
<h3><%=t '.title', :default => model_class.model_name.human.pluralize %>: <%= number_to_currency(sum_portfolio) %></h3>
</div>
<table class="table table-striped table-bordered">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:symbol) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:price) %></th>
      <th><%= model_class.human_attribute_name(:bid) %></th>
      <th><%= model_class.human_attribute_name(:qty) %></th>
      <th>Gain</th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @holdings.each do |holding| %>
      <tr>
        <td><b><%= link_to holding.symbol, holding_path(holding) %></b></td>
        <td><%= holding.name %></td>
        <td><%= number_to_currency(holding.price) %></td>
        <td><%= number_to_currency(holding.bid) %></td>
        <td><%= holding.qty %></td>
        <td><%= number_to_currency(holding.gain) %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_holding_path(holding), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      holding_path(holding),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/holdings/new.html.erb
<%- model_class = Holding -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "New #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/holdings/show.html.erb
<%- model_class = Holding -%>
<div class="page-header">
  <h3><%=t '.title', :default => model_class.model_name.human %>: <%= @holding.symbol %></h3>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:price) %>:</strong></dt>
  <dd><%= number_to_currency(@holding.price) %></dd>
  <dt><strong><%= model_class.human_attribute_name(:qty) %>:</strong></dt>
  <dd><%= @holding.qty %></dd>
  <dt><strong><%= model_class.human_attribute_name(:ask) %>:</strong></dt>
  <dd><%= number_to_currency(@holding.ask) %></dd>
  <dt><strong><%= model_class.human_attribute_name(:bid) %>:</strong></dt>
  <dd><%= number_to_currency(@holding.bid) %></dd>
  <dt><strong><%= model_class.human_attribute_name(:gain) %>:</strong></dt>
  <dd><%= number_to_currency(@holding.gain) %></dd>
  <dt><strong><%= model_class.human_attribute_name(:daily_low) %>:</strong></dt>
  <dd><%= number_to_currency(@holding.daily_low) %></dd>
  <dt><strong><%= model_class.human_attribute_name(:daily_high) %>:</strong></dt>
  <dd><%= number_to_currency(@holding.daily_high) %></dd>
  <dt><strong><%= model_class.human_attribute_name(:notes) %>:</strong></dt>
  <dd><%= @holding.notes %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              holdings_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_holding_path(@holding), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              holding_path(@holding),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <!-- Add the version number to the title -->
  <title>Portfolio Manager <%= APP_VERSION %></title>
  <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
  <![endif]-->
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width", initial-scale=1.0">
</head>
<body>
  <div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
    <div class="container">
      
 
      <!-- .btn-navbar is used as the toggle for collapsed navbar content -->
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
 
      <!-- Be sure to leave the brand out there if you want it shown -->
      <%= link_to 'Portolio Manager', holdings_path, :class => 'brand' %>
      <div class="nav-collapse"> 
        <div class="pull-right">
          <%= link_to 'New Holding', new_holding_path(@holding), :class => 'btn btn-mini' %>
        </div>
      </div>
      <!-- Everything you want hidden at 940px or less, place within here -->
      <div class="nav-collapse collapse">
        <!-- .nav, .navbar-search, .navbar-form, etc -->
      </div>
 
    </div>
  </div>
  </div>
  <div class="container">
    <div class="row">
      <div class="span12">
        <%= yield %>
      </div>
    </div>
  </div>
</body>
</html>